In [13]:
import sys
import numpy as np

def remove_combinations(can_use_as_column, current, new_column, d):
	colums_cnt = len(current)
	for i in range(1, min(d - 2, colums_cnt + 1)):
		remove_combination(can_use_as_column, current, new_column, i, colums_cnt)

def remove_combination(can_use_as_column, current, new_column, length, colums_cnt):
	combinations = [-1] * length
	k = 0
	while k >= 0:
		combinations[k] += 1
		k += 1
		while k < length:
			combinations[k] = combinations[k - 1] + 1
			k += 1

		remove = new_column
		for i in range(0, length):
			remove ^= current[combinations[i]]
		can_use_as_column[remove] = False

		k = length - 1
		while k >= 0 and combinations[k] >= colums_cnt - 1:
			colums_cnt -= 1
			k -= 1

def get_varhalamov_hilbert_boundary(n, k):
	level = 1 << (n - k)

	d = 1
	current = n

	while level > current:
		diff = n - 1
		i = min(n - d - 1, d)
		while i > 1:
			i -= 1
			diff *= (n - 1 - i) / i
		current += diff
		d += 1
	return d + 1

def get_code(n, k, d):
	r = n - k
	length = 1 << r
	can_use_as_column = [True] * length
	can_use_as_column[0] = False
	current = []
	remaining = n
	i = 1
	while i < length and remaining > 0:
		can_use_as_column[i] = False
		remove_combinations(can_use_as_column, current, i, d)

		current.append(i)
		remaining -= 1

		while i < length and not can_use_as_column[i]:
			i += 1

	if len(current) < n:
		return False
	return current

n = 10
k = 5
d = get_varhalamov_hilbert_boundary(n, k)

if d < 3:
    print("Code is trivial")
    return

code = get_code(n, k, d)

if code is None:
	print(f"Couldn't generate code for n = {n}, k = {k}, d = {d}")
else:
    print(f"n = {n}, k = {k}, d = {d}")
    print(code)
    G = list(map(lambda x: list(map(int, list(bin(x)[2:].zfill(n - k)))), code))
    G = np.array(G)
    G = G.T
    print(G)


n = 10, k = 5, d = 4
[1, 2, 4, 7, 8, 11, 13, 14, 16, 19]
[[0 0 0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1 0 0]
 [0 0 1 1 0 0 1 1 0 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 0 1 0 1 1 0 0 1]]


Разумно использовать программу при n ~ 40, k ~20

Ассимптотическая сложность O(n * d^2 * C_n^d) (худший случай)