In [12]:
import sys
import numpy as np

def collect_combinations(isColumn, current, newItem, d):
	currentLength = len(current)
	for i in range(1, min(d - 2, currentLength + 1)):
		combination(isColumn, current, newItem, i, currentLength)

def combination(isColumn, current, newItem, byNumber, currentLength):
	combinations = [-1] * byNumber
	k = 0
	while k >= 0:
		combinations[k] += 1
		k += 1
		while k < byNumber:
			combinations[k] = combinations[k - 1] + 1
			k += 1

		remove = newItem
		for i in range(0, byNumber):
			remove ^= current[combinations[i]]
		isColumn[remove] = False

		k = byNumber - 1
		maxCurrentCol = currentLength - 1
		while k >= 0 and combinations[k] >= maxCurrentCol:
			maxCurrentCol -= 1
			k -= 1

def get_varhalamov_hilbert_boundary(n, k):
	level = 1 << (n - k)

	d = 1 # will add 2 before return
	current = n

	while level > current:
		diff = n - 1
		i = min(n - d - 1, d)
		while i > 1:
			i -= 1
			# calc combination numbers iteratively
			diff *= (n - 1 - i) / i
		current += diff
		d += 1
	return d + 1

def calcCode(n, k, d):
	r = n - k
	length = 1 << r
	isColumn = [True] * length
	isColumn[0] = False
	current = []
	remaining = n
	i = 1
	while i < length and remaining > 0:
		isColumn[i] = False
		collect_combinations(isColumn, current, i, d)

		current.append(i)
		remaining -= 1

		while i < length and not isColumn[i]:
			i += 1

	if len(current) < n:
		return False
	return current

n = 10
k = 5
d = get_varhalamov_hilbert_boundary(n, k)

if d < 3:
    print("Code is trivial")
    return

code = calcCode(n, k, d)

if not code:
	print(f"Couldn't generate code for n = {n}, k = {k}, d = {d}")
else:
    print(f"n = {n}, k = {k}, d = {d}")
    print(code)
    G = list(map(lambda x: list(map(int, list(bin(x)[2:].zfill(n - k)))), code))
    G = np.array(G)
    G = G.T
    print(G)


n = 10, k = 5, d = 4
[1, 2, 4, 7, 8, 11, 13, 14, 16, 19]
[[0 0 0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1 0 0]
 [0 0 1 1 0 0 1 1 0 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 0 1 0 1 1 0 0 1]]


Разумно использовать программу при n ~ 40, k ~20

Ассимптотическая сложность O(n * d^2 * C_n^d) (худший случай)